/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhasIdeiasRouteImport } from './routes/minhas-ideias'
import { Route as ObjetivosRouteImport } from './routes/objetivos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as AvaliacoesIndexRouteImport } from './routes/avaliacoes/index'
import { Route as AvaliacoesIdeaIdRouteImport } from './routes/avaliacoes/$ideaId'
import { Route as DesafiosIndexRouteImport } from './routes/desafios/index'
import { Route as DesafiosChallengeIdRouteImport } from './routes/desafios/$challengeId'
import { Route as DesafiosNovoRouteImport } from './routes/desafios/novo'
import { Route as ExplorarIndexRouteImport } from './routes/explorar/index'
import { Route as ExplorarChallengeIdRouteImport } from './routes/explorar/$challengeId'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelChallengeIdRouteImport } from './routes/painel/$challengeId'
import { Route as ProgramasIndexRouteImport } from './routes/programas/index'
import { Route as ProgramasProgramIdRouteImport } from './routes/programas/$programId'
import { Route as ProgramasNovoRouteImport } from './routes/programas/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasIdeiasRoute = MinhasIdeiasRouteImport.update({
  id: '/minhas-ideias',
  path: '/minhas-ideias',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivosRoute = ObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesIndexRoute = AvaliacoesIndexRouteImport.update({
  id: '/avaliacoes/',
  path: '/avaliacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesIdeaIdRoute = AvaliacoesIdeaIdRouteImport.update({
  id: '/avaliacoes/$ideaId',
  path: '/avaliacoes/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosIndexRoute = DesafiosIndexRouteImport.update({
  id: '/desafios/',
  path: '/desafios/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosChallengeIdRoute = DesafiosChallengeIdRouteImport.update({
  id: '/desafios/$challengeId',
  path: '/desafios/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosNovoRoute = DesafiosNovoRouteImport.update({
  id: '/desafios/novo',
  path: '/desafios/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarIndexRoute = ExplorarIndexRouteImport.update({
  id: '/explorar/',
  path: '/explorar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarChallengeIdRoute = ExplorarChallengeIdRouteImport.update({
  id: '/explorar/$challengeId',
  path: '/explorar/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelChallengeIdRoute = PainelChallengeIdRouteImport.update({
  id: '/painel/$challengeId',
  path: '/painel/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasIndexRoute = ProgramasIndexRouteImport.update({
  id: '/programas/',
  path: '/programas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasProgramIdRoute = ProgramasProgramIdRouteImport.update({
  id: '/programas/$programId',
  path: '/programas/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasNovoRoute = ProgramasNovoRouteImport.update({
  id: '/programas/novo',
  path: '/programas/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minhas-ideias': typeof MinhasIdeiasRoute
  '/objetivos': typeof ObjetivosRoute
  '/usuarios': typeof UsuariosRoute
  '/avaliacoes/$ideaId': typeof AvaliacoesIdeaIdRoute
  '/desafios/$challengeId': typeof DesafiosChallengeIdRoute
  '/desafios/novo': typeof DesafiosNovoRoute
  '/explorar/$challengeId': typeof ExplorarChallengeIdRoute
  '/painel/$challengeId': typeof PainelChallengeIdRoute
  '/programas/$programId': typeof ProgramasProgramIdRoute
  '/programas/novo': typeof ProgramasNovoRoute
  '/avaliacoes/': typeof AvaliacoesIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/explorar/': typeof ExplorarIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/programas/': typeof ProgramasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minhas-ideias': typeof MinhasIdeiasRoute
  '/objetivos': typeof ObjetivosRoute
  '/usuarios': typeof UsuariosRoute
  '/avaliacoes/$ideaId': typeof AvaliacoesIdeaIdRoute
  '/desafios/$challengeId': typeof DesafiosChallengeIdRoute
  '/desafios/novo': typeof DesafiosNovoRoute
  '/explorar/$challengeId': typeof ExplorarChallengeIdRoute
  '/painel/$challengeId': typeof PainelChallengeIdRoute
  '/programas/$programId': typeof ProgramasProgramIdRoute
  '/programas/novo': typeof ProgramasNovoRoute
  '/avaliacoes': typeof AvaliacoesIndexRoute
  '/desafios': typeof DesafiosIndexRoute
  '/explorar': typeof ExplorarIndexRoute
  '/painel': typeof PainelIndexRoute
  '/programas': typeof ProgramasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minhas-ideias': typeof MinhasIdeiasRoute
  '/objetivos': typeof ObjetivosRoute
  '/usuarios': typeof UsuariosRoute
  '/avaliacoes/$ideaId': typeof AvaliacoesIdeaIdRoute
  '/desafios/$challengeId': typeof DesafiosChallengeIdRoute
  '/desafios/novo': typeof DesafiosNovoRoute
  '/explorar/$challengeId': typeof ExplorarChallengeIdRoute
  '/painel/$challengeId': typeof PainelChallengeIdRoute
  '/programas/$programId': typeof ProgramasProgramIdRoute
  '/programas/novo': typeof ProgramasNovoRoute
  '/avaliacoes/': typeof AvaliacoesIndexRoute
  '/desafios/': typeof DesafiosIndexRoute
  '/explorar/': typeof ExplorarIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/programas/': typeof ProgramasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/minhas-ideias'
    | '/objetivos'
    | '/usuarios'
    | '/avaliacoes/$ideaId'
    | '/desafios/$challengeId'
    | '/desafios/novo'
    | '/explorar/$challengeId'
    | '/painel/$challengeId'
    | '/programas/$programId'
    | '/programas/novo'
    | '/avaliacoes/'
    | '/desafios/'
    | '/explorar/'
    | '/painel/'
    | '/programas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/minhas-ideias'
    | '/objetivos'
    | '/usuarios'
    | '/avaliacoes/$ideaId'
    | '/desafios/$challengeId'
    | '/desafios/novo'
    | '/explorar/$challengeId'
    | '/painel/$challengeId'
    | '/programas/$programId'
    | '/programas/novo'
    | '/avaliacoes'
    | '/desafios'
    | '/explorar'
    | '/painel'
    | '/programas'
  id:
    | '__root__'
    | '/'
    | '/minhas-ideias'
    | '/objetivos'
    | '/usuarios'
    | '/avaliacoes/$ideaId'
    | '/desafios/$challengeId'
    | '/desafios/novo'
    | '/explorar/$challengeId'
    | '/painel/$challengeId'
    | '/programas/$programId'
    | '/programas/novo'
    | '/avaliacoes/'
    | '/desafios/'
    | '/explorar/'
    | '/painel/'
    | '/programas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinhasIdeiasRoute: typeof MinhasIdeiasRoute
  ObjetivosRoute: typeof ObjetivosRoute
  UsuariosRoute: typeof UsuariosRoute
  AvaliacoesIdeaIdRoute: typeof AvaliacoesIdeaIdRoute
  DesafiosChallengeIdRoute: typeof DesafiosChallengeIdRoute
  DesafiosNovoRoute: typeof DesafiosNovoRoute
  ExplorarChallengeIdRoute: typeof ExplorarChallengeIdRoute
  PainelChallengeIdRoute: typeof PainelChallengeIdRoute
  ProgramasProgramIdRoute: typeof ProgramasProgramIdRoute
  ProgramasNovoRoute: typeof ProgramasNovoRoute
  AvaliacoesIndexRoute: typeof AvaliacoesIndexRoute
  DesafiosIndexRoute: typeof DesafiosIndexRoute
  ExplorarIndexRoute: typeof ExplorarIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  ProgramasIndexRoute: typeof ProgramasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-ideias': {
      id: '/minhas-ideias'
      path: '/minhas-ideias'
      fullPath: '/minhas-ideias'
      preLoaderRoute: typeof MinhasIdeiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivos': {
      id: '/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof ObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/': {
      id: '/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/avaliacoes/'
      preLoaderRoute: typeof AvaliacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes/$ideaId': {
      id: '/avaliacoes/$ideaId'
      path: '/avaliacoes/$ideaId'
      fullPath: '/avaliacoes/$ideaId'
      preLoaderRoute: typeof AvaliacoesIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/': {
      id: '/desafios/'
      path: '/desafios'
      fullPath: '/desafios/'
      preLoaderRoute: typeof DesafiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/$challengeId': {
      id: '/desafios/$challengeId'
      path: '/desafios/$challengeId'
      fullPath: '/desafios/$challengeId'
      preLoaderRoute: typeof DesafiosChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios/novo': {
      id: '/desafios/novo'
      path: '/desafios/novo'
      fullPath: '/desafios/novo'
      preLoaderRoute: typeof DesafiosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar/': {
      id: '/explorar/'
      path: '/explorar'
      fullPath: '/explorar/'
      preLoaderRoute: typeof ExplorarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar/$challengeId': {
      id: '/explorar/$challengeId'
      path: '/explorar/$challengeId'
      fullPath: '/explorar/$challengeId'
      preLoaderRoute: typeof ExplorarChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$challengeId': {
      id: '/painel/$challengeId'
      path: '/painel/$challengeId'
      fullPath: '/painel/$challengeId'
      preLoaderRoute: typeof PainelChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/': {
      id: '/programas/'
      path: '/programas'
      fullPath: '/programas/'
      preLoaderRoute: typeof ProgramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/$programId': {
      id: '/programas/$programId'
      path: '/programas/$programId'
      fullPath: '/programas/$programId'
      preLoaderRoute: typeof ProgramasProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/novo': {
      id: '/programas/novo'
      path: '/programas/novo'
      fullPath: '/programas/novo'
      preLoaderRoute: typeof ProgramasNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinhasIdeiasRoute: MinhasIdeiasRoute,
  ObjetivosRoute: ObjetivosRoute,
  UsuariosRoute: UsuariosRoute,
  AvaliacoesIdeaIdRoute: AvaliacoesIdeaIdRoute,
  DesafiosChallengeIdRoute: DesafiosChallengeIdRoute,
  DesafiosNovoRoute: DesafiosNovoRoute,
  ExplorarChallengeIdRoute: ExplorarChallengeIdRoute,
  PainelChallengeIdRoute: PainelChallengeIdRoute,
  ProgramasProgramIdRoute: ProgramasProgramIdRoute,
  ProgramasNovoRoute: ProgramasNovoRoute,
  AvaliacoesIndexRoute: AvaliacoesIndexRoute,
  DesafiosIndexRoute: DesafiosIndexRoute,
  ExplorarIndexRoute: ExplorarIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  ProgramasIndexRoute: ProgramasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
